### ISSUE TITLE
start the program

### ISSUE THREAD

**Issue by NoSoyDany** [CShark/obs-better-multiview#1]
how can I start the program?

**Comment by CShark** [comment]
Usually by just starting the exe file. If that does not work, can you post the log file?

**Comment by CShark** [comment]
And you need to have [OBS-Websocket](https://github.com/obsproject/obs-websocket/releases/tag/4.9.1) installed. The zip file of this project itself can be unpacked anywhere.

**Comment by NoSoyDany** [comment]
> Usually by just starting the exe file. If that does not work, can you post the log file?

I can't find it (exe file)

**Comment by CShark** [comment]
It's packed inside the zip-file under releases. There is no installer or something similar, you can just unpack the zip anywhere.
